// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
   
   
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_jd5RT-I5x19QyWnbmZaXZ6abdGKr9o',
    appId: '1:1091745949003:web:e159c54454dc9d7d6a34ce',
    messagingSenderId: '1091745949003',
    projectId: 'fasum-nelson',
    authDomain: 'fasum-nelson.firebaseapp.com',
    storageBucket: 'fasum-nelson.firebasestorage.app',
    measurementId: 'G-13W6LYHPCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuCDPqtLAjj1zNfDpVi4A-27AfzV9jB1c',
    appId: '1:1091745949003:android:90052d9d74a296a66a34ce',
    messagingSenderId: '1091745949003',
    projectId: 'fasum-nelson',
    storageBucket: 'fasum-nelson.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYehQRs18mDY8Um1sUEQdondzh6isefbQ',
    appId: '1:1091745949003:ios:8ade41afc972d2806a34ce',
    messagingSenderId: '1091745949003',
    projectId: 'fasum-nelson',
    storageBucket: 'fasum-nelson.firebasestorage.app',
    iosBundleId: 'com.example.fasumNelson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYehQRs18mDY8Um1sUEQdondzh6isefbQ',
    appId: '1:1091745949003:ios:8ade41afc972d2806a34ce',
    messagingSenderId: '1091745949003',
    projectId: 'fasum-nelson',
    storageBucket: 'fasum-nelson.firebasestorage.app',
    iosBundleId: 'com.example.fasumNelson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_jd5RT-I5x19QyWnbmZaXZ6abdGKr9o',
    appId: '1:1091745949003:web:aeefe8edcaeffb046a34ce',
    messagingSenderId: '1091745949003',
    projectId: 'fasum-nelson',
    authDomain: 'fasum-nelson.firebaseapp.com',
    storageBucket: 'fasum-nelson.firebasestorage.app',
    measurementId: 'G-8Z2GLVEF2C',
  );

}